theme: jekyll-theme-minimal
title: Computational modelling of cellular mechanics
description: International Conference on Computational Science 2023
location: Prague, Czech Republic, 3-5 July, 2023
logo: assets/img/cancer_cell.jpg
show_downloads: false
google_analytics:
